### PR TITLE
Script crash for non-ascii character(s) in username fixed

### PR DESCRIPTION
**Pull request by FortuneNT**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Seriously not the proper way to do this

**Comment by MartijnKaijser** [comment]
Could still have non ascii letters when running in portable mode

**Comment by ronie** [comment]
not familiar with this addon, but using this might be a good start:
`_doc = parse(xbmc.translatePath(PLAYLIST)).decode("utf-8")`

**Comment by FortuneNT** [comment]
You right, but I also think it is not an add-on related issue, I have this problem with multiple add-ons.
I unfortunately couldn't figure out a solution for the entire Kodi project.
Even though this is a fair enough solution for non-portable versions for this specific add-on.

Ronie nice suggestion but that doesn't work.

**Comment by MartijnKaijser** [comment]
Put the decode between the parse brackets.most add-ons use this so it should work.

**Comment by FortuneNT** [comment]
That works indeed.
I thought I already tried that, but apparently i didn't.
That should only be done on windows systems right?
Like explained here: http://kodi.wiki/view/Add-on_unicode_paths

**Comment by MartijnKaijser** [comment]
No its platform independent and doesn't hurt

**Comment by FortuneNT** [comment]
Thanks for the feedback I changed it.

**Pull request closed without merging**
